### ISSUE TITLE
[FE] - Glitch between login and monitor page

### ISSUE THREAD

**Issue by marcelluscaio** [bluewave-labs/checkmate#1122]
**Describe the bug**
After we login, we can see the login page for about half a second. That seems to be happening because of the protectedRoute component. It needs to get the auth information from redux, and that takes a while since it was recently updated.

**To Reproduce**
Logout. Open the performance tab on devtools, and record. Login, and when monitor page appears, stop recording. See there is a glitch between login and the monitor page.

**Expected behavior**
It should provide some sort of loading, and then navigate to the page.

**Additional context**
I believe there are two things to be done: on the login page, we can add a loading state while user information is not updated, before redirecting.
Also, we could provide a loading state while user is undefined in protectedRoute, for about two seconds. That path may never be reached with what we set in the login phase, but it would be an extra layer of protection

**Comment by crunchydosa123** [comment]
Hi, is this taken?

**Comment by gorkem-bwl** [comment]
Nope, go ahead please. Before starting, write how you are going to implement it.

**Comment by crunchydosa123** [comment]
I will start with the suggestion given on your description for this issue. Any notes for cloning the repo and running on localhost?

**Comment by gorkem-bwl** [comment]
> I will start with the suggestion given on your description for this issue. Any notes for cloning the repo and running on localhost?

All the details are in our readme.md file, which also has a section that links to our documentation.

**Comment by gorkem-bwl** [comment]
@crunchydosa123 let me know if you are moving forward with this issue. Thanks.

**Comment by crunchydosa123** [comment]
Yes

**Comment by crunchydosa123** [comment]
hey, while trying to replicate the issue, do i need to run the docker containers for backend as well? or is there a way i can simulate it by running using just vite?

**Comment by marcelluscaio** [comment]
I think it's best if you run the whole project. I don't think you'll be able to login without a backend
