### ISSUE TITLE
Password reset panel incorrect error message

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/checkmate#1206]
This error message should be something like "this field can't be empty" 

![image](https://github.com/user-attachments/assets/2c1e3000-270f-40c9-ab98-6d5f4b9f8259)

**Comment by Shreyashingale** [comment]
hey @ajhollid can you assign this to me!

**Comment by ajhollid** [comment]
@Shreyashingale sure, it's all yours

**Comment by Shreyashingale** [comment]
Thanks I'll start working on it

**Comment by Shreyashingale** [comment]
@ajhollid can you mention the steps to reproduce the issue

**Comment by ajhollid** [comment]
> @ajhollid can you mention the steps to reproduce the issue

Hi @Shreyashingale ,

Just head on over to the account panel at `account/password`, type something in to the "confirm password" input field, then erase it.  You'll be presented with the "empty" message

**Comment by Shreyashingale** [comment]
@ajhollid "For setting up the server, do we need to create both MongoDB and Redis databases, or is there a different way we should manage this? I'm following the environmental variables section from the link you shared."

or how can we manage the .env file required parameters



following : https://bluewavelabs.gitbook.io/checkmate/users-guide/quickstart#server-setup

**Comment by ajhollid** [comment]
> @ajhollid "For setting up the server, do we need to create both MongoDB and Redis databases, or is there a different way we should manage this? I'm following the environmental variables section from the link you shared."
> 
> or how can we manage the .env file required parameters
> 
> following : https://bluewavelabs.gitbook.io/checkmate/users-guide/quickstart#server-setup

Hi @Shreyashingale ,

Yes both a MongoDB database and Redis database are required to run the app.  You can use our included docker images if you like, or run your own locally.

There are two `.env` files required for a local build, one in your `Client` directory and one in your `Server` directory

**Comment by peterpardo** [comment]
Hello! Is this currently being worked on right now?

**Comment by gorkem-bwl** [comment]
> Hello! Is this currently being worked on right now?

Currently @Shreyashingale is working on it, but if we don't hear from him until tomorrow, feel free to take this task over.

**Comment by Shreyashingale** [comment]
@gorkem-bwl  please let @peterpardo take over for now. I am facing some issues with setting up the environment meanwhile I'll try to resolve them and get an understanding of the project.
thank you.

**Comment by gorkem-bwl** [comment]
> @gorkem-bwl please let @peterpardo take over for now. I am facing some issues with setting up the environment meanwhile I'll try to resolve them and get an understanding of the project. thank you.

Thanks for letting me know about this. When you have the project get set up, happy to have you here again for new tasks!

**Comment by gorkem-bwl** [comment]
Good with that - please send a PR.
