### ISSUE TITLE
Version conflict between @mui/material v6.x and @mui/icons-material v5.x During npm Install

### ISSUE THREAD

**Issue by peterpardo** [bluewave-labs/checkmate#1213]
**Describe the bug**
I forked the project and tried to run it in my local machine. I am following the [Quickstart for developers](https://bluewavelabs.gitbook.io/checkmate/users-guide/quickstart#dev-quickstart) to set it up in my machine. When I ran the _build_images.sh_ file,  it showed an error when it was running the _client.Dockerfile_, specifically when it was running the _npm install_ command. It's showing an error about the **@mui/material** version mismatch.

**To Reproduce**
1. Fork the **bluewave-labs/checkmate** repo
2. Clone the repo into your local machine
3. Open the project, then change the directory to the `Docker/dev`
4. Run the `build_images.sh` script

**Expected behavior**
Executing the `build_images.sh` file should be successful without any errors.

**Screenshots**
This is how the terminal looks after running `build_images.sh` script
![image](https://github.com/user-attachments/assets/d674c8af-e456-48b4-907c-c2ccb74542b1)

**Desktop (please complete the following information):**
 - Chrome
 - Version 131.0.6778.86

**Additional context**
If the steps to reproduce are unclear, you can do the [Quickstart for developers](https://bluewavelabs.gitbook.io/checkmate/users-guide/quickstart#dev-quickstart)

**Comment by ajhollid** [comment]
Hi @peterpardo, this has been resolved in a PR yesterday, please pull the latest develop branch and you should be good to go.  Thanks for the heads up!

**Comment by ajhollid** [comment]
> this

No problem, thank you for taking the time to report it!
