### ISSUE TITLE
Infrastructure monitor page content is wider than Monitors or Pagespeed

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1241]
Comparison: 

<img width="547" alt="image" src="https://github.com/user-attachments/assets/bc200ac6-3ab8-4e10-b0bf-1213c880a9a2">

vs

<img width="527" alt="image" src="https://github.com/user-attachments/assets/78589845-f3d1-4d01-ab33-e557f7f2fe5a">

**Comment by peterpardo** [comment]
Hello! Is this issue already being worked on? I can work on this if that's ok.

**Comment by gorkem-bwl** [comment]
Sure, Peter. We are about to make a release so if you can do it in the next couple of hours - that would be great!

**Comment by peterpardo** [comment]
Cool! Let me work on it. Thanks!
