### ISSUE TITLE
Disabled Button Color 

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/checkmate#1242]
Dark theme disabled button color needs adjustment:

![image](https://github.com/user-attachments/assets/90d227b2-4512-4d77-98d9-b905af945572)

Light theme appears to be OK:

![image](https://github.com/user-attachments/assets/1eb0a58e-17a0-487b-88e1-4e29f3a74497)

**Comment by paulinezhanghh** [comment]
@ajhollid Hi! I'm interested in working on this issue. Can I take this one?

**Comment by gorkem-bwl** [comment]
@paulinezhanghh please go ahead. As we are nearing the release, can you make a fix soon?

**Comment by paulinezhanghh** [comment]
> @paulinezhanghh please go ahead. As we are nearing the release, can you make a fix soon?

I will try my best to finish it soon. Is there a deadline that you want me to fix this?

**Comment by gorkem-bwl** [comment]
> > @paulinezhanghh please go ahead. As we are nearing the release, can you make a fix soon?
> 
> I will try my best to finish it soon. Is there a deadline that you want me to fix this?

If possible, today. If not, early tomorrow :)

**Comment by marcelluscaio** [comment]
@paulinezhanghh I opened a PR for this one because of the release deadline. Thank you for your interest in helping the project
