### ISSUE TITLE
FE - Disabled Text Field Colors

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/checkmate#1257]
Disabled text in a text field is not visible:

![Screenshot from 2024-12-03 10-04-53](https://github.com/user-attachments/assets/92d34276-3699-4614-84c1-2af5c36a96f7)

![Screenshot from 2024-12-03 10-05-19](https://github.com/user-attachments/assets/c789fe40-4eaa-41a1-9e89-5dd7a20abf07)

This can be resolved by explicitly setting a color for disabled text in the theme:

```
"& .MuiInputBase-input.Mui-disabled": {
	color: theme.palette.text.disabled,
	"-webkit-text-fill-color": theme.palette.text.disabled,
},
```

Additionally I am not sure if this is the correct border color for a disabled field?  It should probably be a grey?

@gorkem-bwl could you please clarify on color schemes here?  Thanks!

**Comment by gorkem-bwl** [comment]
Yes, it was a grey field border before as far as I remember. @marcelluscaio can you please come up with an appropriate color scheme as I am not really good at assigning colors for the dark mode? 

We need to get this done for 2.0, so adding a milestone there.
