### ISSUE TITLE
"Administrator" should be "Super admin"

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1268]
There is a small discrepancy with the naming of the admin. In the table we have "Administrator" but the row in the table suggests it is "Super admin". Since the backend probably knows it's Super Admin, it is easy to modify the string "Administrator" to "Super admin" on the table itself.

<img width="1375" alt="image" src="https://github.com/user-attachments/assets/a9523b18-0ba7-48dc-81eb-4b298dbfc286">

**Comment by Ankush1oo8** [comment]
This code is located in client/ team panel right

**Comment by gorkem-bwl** [comment]
Yes. Please make sure you run the app as well, and send a corresponding screenshot after you are done with the PR.

**Comment by Shaikh-Mudassir** [comment]
I would like to contribute to it. and make the necessary changes.

**Comment by gorkem-bwl** [comment]
> I would like to contribute to it. and make the necessary changes.

Let's wait for @Ankush1oo8 to respond to the latest conversation.

**Comment by Ankush1oo8** [comment]
Yes I am working on it

**Comment by Ankush1oo8** [comment]
fixed the issue by following PR
 fix : "Administrator" changed to "Super admin" in TeamPanel #1283

**Comment by gorkem-bwl** [comment]
Thanks for this - we'll review and merge.
