### ISSUE TITLE
Add gap between label and inputs

### ISSUE THREAD

**Issue by marcelluscaio** [bluewave-labs/checkmate#1270]
On smaller screens label and input touch on the profile form

![Screenshot 2024-12-03 191712](https://github.com/user-attachments/assets/efc1a088-e1cb-48e0-8a22-5d7be3b7c6b0)

**Comment by Shaikh-Mudassir** [comment]
Hey! I would like to contribute to this issue.

**Comment by gorkem-bwl** [comment]
Sure @Shaikh-Mudassir go ahead please. This doesn't have to go into 2.0, FYI @marcelluscaio

**Comment by Shaikh-Mudassir** [comment]
@gorkem-bwl  Thank you for assigning this issue to me. I have submitted a pull request with the requested modifications. Kindly let me know if any additional changes or adjustments are required.

**Comment by ajhollid** [comment]
![image](https://github.com/user-attachments/assets/70425e27-33bb-4cd0-b5d5-032f82b1ab96)

I don't think this has been fully resovled yet, the label is still touching the input here
