### ISSUE TITLE
Password validation on Account > Password

### ISSUE THREAD

**Issue by marcelluscaio** [bluewave-labs/checkmate#1274]
If you type in your password, then add a new password that is incomplete e.g. Ad,tree! (without a number), and set the confirm password to Ad,tree! , and then add  a number e.g. 1 to your password, without changing the confirm password, all validations will pass, even though password and confirm password are different

**Comment by peterpardo** [comment]
Hello! I can knock this one out.

**Comment by ajhollid** [comment]
@peterpardo sure, go for it if you'd like!
