### ISSUE TITLE
Alignment required for "JWT" section (check the text edit field and dropdown) 

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1289]
<img width="887" alt="image" src="https://github.com/user-attachments/assets/332ad382-bd4f-464f-8b72-6201cc4f9abd">

**Comment by gauravnadkarni** [comment]
Hi @gorkem-bwl, Can i take this up?
For clarification: This is about aligning the `JWT TTL units` dropdown on the same line with `JWT time to live` text box, correct?

**Comment by ajhollid** [comment]
@gauravnadkarni sure, open up a PR whenever you're ready!

**Comment by gorkem-bwl** [comment]
Looks good!
