### ISSUE TITLE
Dark mode switcher before login and inside dashboard

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1317]
We need a dark mode switcher before logging in and inside the dashboard. Here is a good option: https://web.dev/patterns/theming/theme-switch

It can be added here for login: 

<img width="611" alt="image" src="https://github.com/user-attachments/assets/8d809e4d-5c19-4568-bae5-75bd404ea690">

And here for the dashboard:

<img width="345" alt="image" src="https://github.com/user-attachments/assets/898573f6-5ee2-4d10-9e1f-671adefcdb5e">

**Comment by peterpardo** [comment]
Hello! I can work on this.

In this issue, do we also include the functionality of the dark mode switcher?

**Comment by gorkem-bwl** [comment]
Hi Peter. Yes, we need that functionality. Let me know if you still would like to work on it.

**Comment by peterpardo** [comment]
Got it. I can work on this one.

**Comment by peterpardo** [comment]
For the dark mode switch in the Dashboard, do you want to place it on the left of the `ellipsis vertical` icon?

**Comment by ajhollid** [comment]
> For the dark mode switch in the Dashboard, do you want to place it on the left of the `ellipsis vertical` icon?

Hi @peterpardo ,

Yes I believe that is the idea

**Comment by gorkem-bwl** [comment]
@peterpardo it might be a bit tricky so please share you screenshots/videos here as you progress :)

**Comment by peterpardo** [comment]
I was researching dark mode in Material UI, and I came across this approach: https://mui.com/material-ui/customization/dark-mode/#dark-mode-only

Then while navigating through the source code,  I saw this comment regarding changing how we implement themes in the app.
![image](https://github.com/user-attachments/assets/85b41d2f-8bf6-48d9-9405-5cd2bcd3d121)

Do we want to include these changes in this issue as well?

**Comment by gorkem-bwl** [comment]
If it is directly related to this issue, you can include it. If you can separate them (e.g implement #1317 and then move on to this one), that is easier to review and merge I assume.

**Comment by peterpardo** [comment]
Got it. I think for this issue, we can add the dark mode switcher without the functionality for now. Then create another PR for the functionality which will include the TODO in the comment. What do you think?

**Comment by gorkem-bwl** [comment]
> Got it. I think for this issue, we can add the dark mode switcher without the functionality for now. Then create another PR for the functionality which will include the TODO in the comment. What do you think?

Let's go then!

**Comment by peterpardo** [comment]
Hello! Here is the progress for the dark mode switch:

**In the `Login` page**:
https://github.com/user-attachments/assets/5550d827-3c97-49eb-ab35-9f6b102e365f

**In the `Sidebar`**:
https://github.com/user-attachments/assets/b383711e-c3c3-484d-8d43-13da7b686ac1

What do you think?

**Comment by gorkem-bwl** [comment]
> Hello! Here is the progress for the dark mode switch:
> 
> **In the `Login` page**: https://github.com/user-attachments/assets/5550d827-3c97-49eb-ab35-9f6b102e365f
> 
> **In the `Sidebar`**: https://github.com/user-attachments/assets/b383711e-c3c3-484d-8d43-13da7b686ac1
> 
> What do you think?

I think they look great. 

After this PR we need to remove it from the main settings area (where the dark/light switcher currently is).

**Comment by peterpardo** [comment]
Got it. I'll proceed to publish the PR. Thank you!

**Comment by gorkem-bwl** [comment]
> I already included the dark mode functionality in the PR since there are only few changes that I made to make it work.

Meaning the PR contains full UI + functionality right?

**Comment by peterpardo** [comment]
> > I already included the dark mode functionality in the PR since there are only few changes that I made to make it work.
> 
> Meaning the PR contains full UI + functionality right?

Yep!

**Comment by gorkem-bwl** [comment]
Great, thanks. Let's add it to our next minor release then, if the review process is positive.
