### ISSUE TITLE
Height of the search bar should be 34px (same as other line edit inputs in our Components)

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1322]
Screenshot:

<img width="885" alt="image" src="https://github.com/user-attachments/assets/9273b914-a908-4d0e-a54a-d7776ab36e24">

**Comment by peterpardo** [comment]
Hello! I can work on this.

**Comment by ajhollid** [comment]
@peterpardo sure go for it 👍
