### ISSUE TITLE
Monitors > Monitor details > Average response time chart color issue

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1328]
The following chart looks incomplete (the bigger arc has #FFFFFE color which is almost invisible)

<img width="484" alt="image" src="https://github.com/user-attachments/assets/70c407b0-1dbe-4719-9ecf-b5da95560097">

**Comment by peterpardo** [comment]
Hello! I can work on this.

What color should the bigger arc be in this case?

**Comment by gorkem-bwl** [comment]
Goodp point :) Do you see any arc colors in previous commits that were overriden? I fail to see them (due to my incompetence in reading commits). If you can find the one that has been overridden, that is fine. If you can't, use  #EBA8A9 

Thanks.

**Comment by peterpardo** [comment]
> Goodp point :) Do you see any arc colors in previous commits that were overriden? I fail to see them (due to my incompetence in reading commits). If you can find the one that has been overridden, that is fine. If you can't, use #EBA8A9
> 
> Thanks.

I found the the color that's being used for the arc:

![image](https://github.com/user-attachments/assets/1b850544-5051-4c58-9d1c-eb483a8089db)

The `contrastText` is the only one using the gray colors under the `errors` color palette.

It's under `Client/src/Utils/Theme/constants.js`

Do we want to create a new **red** color using the #EBA8A9 as the value and use it for the arc? Or should we use the other red colors that we have right now in the palette?

**Comment by gorkem-bwl** [comment]
I think EBA8A9 is a better color for that purpose, so we can use it.
