### ISSUE TITLE
"Monitors" should be "Uptime"

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1333]
Since "Monitors" is now a generic name, we should change the wording to "Uptime". 

<img width="903" alt="image" src="https://github.com/user-attachments/assets/31b852ef-2567-4737-9bfe-1eebb88194b6">

**Comment by felixiho** [comment]
hey @ajhollid 
Could you assign this to me ?

**Comment by ajhollid** [comment]
Hi @felixiho ,

Thanks for your interest in the project, this issue has already been resolved however!  Please check out other issues in the log if you'd like to contribute :+1:
