### ISSUE TITLE
Red button mouse hover status has wrong color

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1335]
Mouseover color must be #912018 for light theme. 

<img width="301" alt="image" src="https://github.com/user-attachments/assets/6db12582-11a8-48f6-a59c-2730b8147cf6">

**Comment by nakul-py** [comment]
Hi @gorkem-bwl 
I came across this issue and would like to work on resolving it. Could you please assign it to me?
