### ISSUE TITLE
"Usage" wording consistency

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1350]
Fix "Usage" -> "usage" for Memory and CPU here: 

<img width="699" alt="image" src="https://github.com/user-attachments/assets/d1ccb522-8a6c-4111-8db8-752a3a534874">

**Comment by INDHU1402** [comment]
Hello @gorkem-bwl
I came across this issue and would like to work on resolving it. Could you please assign it to me ?

**Comment by ajhollid** [comment]
Hi @INDHU1402,

Sure, it's all yours

**Comment by INDHU1402** [comment]
Hey, can anyone review the PR ?

**Comment by ajhollid** [comment]
> Hey @ajhollid, can you review the PR ?

Hi @INDHU1402 ,

Yes, we will review PRs as soon as possible.

If they're in the queue we'll get to them!
