### ISSUE TITLE
Email invitation not working

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1377]
When the admin invites a user (email), that user cannot see a signup page but instead a login page. The signup page appears very shortly and then the login page appears.

**Comment by imrehankhan** [comment]
I can try to solve it, assign it to me

**Comment by charlene0505** [comment]
Hi, I'm a 3rd year CS student on break, I'd love to try and solve it! Please assign it to me

**Comment by ajhollid** [comment]
Hi @charlene0505,

There's already a PR open for this issue actually, we'd love your eyes to help review it though if you'd like!   The more PR reviews we have for a given PR the better. 

There are other open issues to look at as well if you're interested 👌

**Comment by Samsonbtc247** [comment]
I just want to secure my sensitive data just a week here it's good easy to learn
