### ISSUE TITLE
Notification message when a monitor is paused

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1380]
When a monitor is paused, there is no visible notification message. We need to show a toast message saying 'This monitor is paused.'

**Comment by Roshan-Singh-07** [comment]
I’m interested in working on this issue:
I’m new to contributing, I’d appreciate your guidance to ensure I’m addressing the issue correctly. Could you help me with the following?

1) How do I trigger the monitor to pause issue? Is it through the UI, an API call, or something else?
2) Once paused, is the toast message supposed to show automatically or only after a specific action?

I’m confident I can solve this but want to make sure I fully understand the problem first.

Thanks in advance for your help, and I’m excited to contribute!

**Comment by ajhollid** [comment]
> I’m interested in working on this issue:
> I’m new to contributing, I’d appreciate your guidance to ensure I’m addressing the issue correctly. Could you help me with the following?
> 
> 1) How do I trigger the monitor to pause issue? Is it through the UI, an API call, or something else?
> 2) Once paused, is the toast message supposed to show automatically or only after a specific action?
> 
> I’m confident I can solve this but want to make sure I fully understand the problem first.
> 
> Thanks in advance for your help, and I’m excited to contribute!

Hi @Roshan-Singh-07 ,

Thanks for your interest in the project!

This issue already has an open PR, if you'd like to contribute we'd love to have you review the PR, the more eyes we have on code the better. 

There are other open issues without PRs if you'd like to contribute there as well.
