### ISSUE TITLE
If there are no team members, add a placeholder

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1400]
If there are no team members in the server, write "There are no team members." instead of showing an empty table. 

Here is an example:

<img width="1023" alt="image" src="https://github.com/user-attachments/assets/7965f05b-d3aa-48fe-bbdb-7e9682c30082" />

**Comment by omarNaifer12** [comment]
@gorkem-bwl Hi, can I work on this?
