### ISSUE TITLE
Add a new uptime monitor > Radio buttons: unselected radio buttons are hard to see

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1404]
When adding a new uptime monitor, radio button component, when unselected, is hard to see. It should match the color of the select button, as seen here:

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/7f0ff0d8-edae-492c-8ea5-332d902c4eec" />

**Comment by Algo-Master** [comment]
I am working on it.

**Comment by bruhathisp** [comment]
Hi team, I’ve created PR #1428 to fix the radio button hover styles. Could someone review it when they have time? Thank you!

**Comment by gorkem-bwl** [comment]
> Hi team, I’ve created PR #1428 to fix the radio button hover styles. Could someone review it when they have time? Thank you!

Currently there is an open PR for this one, so we can wait for him to finish it first, and if it doesn't go through, can look at yours. But as far as I can see you are using hardcoded values and not the theme colors.

**Comment by Algo-Master** [comment]
I have used the **material ui theme** colors to fix the issue, can u review it and inform me if any  changes are required??
Thank u!
