### ISSUE TITLE
When there are no uptime monitors, do not show a skeletion

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1426]
If there are no monitors, the skeleton image still shows up there for a couple of seconds, and then vanishes away. We must make sure to check number of monitors first and then disable showing the skeleton if none exists.

<img width="1390" alt="image" src="https://github.com/user-attachments/assets/3b577e8b-2582-432c-941f-cfd9f0f4d59c" />

**Comment by dhvll** [comment]
Hey @gorkem-bwl I'm interested in this issue ? Can you assign this to me?

**Comment by gorkem-bwl** [comment]
I can reproduce this on our demo server when I login with a superadmin account. Here is another screenshot:

<img width="1407" alt="image" src="https://github.com/user-attachments/assets/e677ab31-1f71-435f-8650-39db3af4f99c" />

This is what I see when I directly login to the dashboard.

**Comment by gorkem-bwl** [comment]
FYI: I also got this momentarily, maybe an issue with Redis? 

<img width="307" alt="image" src="https://github.com/user-attachments/assets/c40e1e6a-9ab7-4cf5-8ca3-e1245b2fbbea" />

**Comment by ajhollid** [comment]
> I can reproduce this on our demo server when I login with a superadmin account. Here is another screenshot:
> 
> <img alt="image" width="1407" src="https://private-user-images.githubusercontent.com/167266851/397491306-e677ab31-1f71-435f-8650-39db3af4f99c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MzMzNDksIm5iZiI6MTczNDYzMzA0OSwicGF0aCI6Ii8xNjcyNjY4NTEvMzk3NDkxMzA2LWU2NzdhYjMxLTFmNzEtNDM1Zi04NjUwLTM5ZGIzYWY0Zjk5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQxODMwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmQzYzY1NDFlMTA5MzJkMTUzMzEzMzE3MDAwNGU2Njc1MGRiMThiZWU2YjAwYjVkODYwNmMwYmQ1MjA2NWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JOK1e1iQQcoweSKF2z2p0rYhGQ_vshtSv_3atFqVuc8">
> This is what I see when I directly login to the dashboard.

Ah ok I see it, it shows up if i throttle my network.
