### ISSUE TITLE
User hamburger menu background should be circle

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1483]
This area should be circle instead of ellipse

<img width="219" alt="image" src="https://github.com/user-attachments/assets/d12d93b7-e28e-4b28-a968-9bd4169a5389" />

**Comment by rafeyrana** [comment]
Hi @gorkem-bwl , i’ve traced this to the IconButton component, please assign the issue to me and I will send in a PR within 24 hours thanks

**Comment by gorkem-bwl** [comment]
@rafeyrana thanks - assigned.
