### ISSUE TITLE
Clicking on settings shouldn't open the "Other" drawer

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1485]
When I click on Settings, the "Other" drawer is opened automatically, which shouldn't be the case. 

<img width="334" alt="image" src="https://github.com/user-attachments/assets/6fd27476-6a4d-4642-be66-b148c1239fa0" />

**Comment by mihirWeb** [comment]
Hi @gorkem-bwl can you assign this issue to me? I'll start working on it.

**Comment by gorkem-bwl** [comment]
Sure, go ahead. Thanks.
