### ISSUE TITLE
Convert status code strings to labels

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#965]
We have a label (chips) component where we can use to identify the status codes in the Incidents table. 

Convert status code into tables where each table has a different color for 403, 502, 5000 and all others. 

Here is the current screenshot of the table where the status codes columns will be converted to labels: 

<img width="1101" alt="image" src="https://github.com/user-attachments/assets/ff635ec6-828c-46a7-83e1-724f55ccab05">

**Comment by d02ev** [comment]
I want to work on this issue.

**Comment by rog404** [comment]
Hello, @gorkem-bwl ,
Can I do this issue?

**Comment by gorkem-bwl** [comment]
> Hello, @gorkem-bwl , Can I do this issue?

Please go ahead. Make sure you use labels in our components directory, install the application on your local, test everything and then commit with a screenshot or a video. Thanks.
