### ISSUE TITLE
Display name should be filled in with the domain name, without the TLD

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#992]
When adding a new monitor, and user adds "URL to monitor", the Display name should be filled in with the URL, without the TLD. The first letter should be capitalized.

Examples: 

https://3dicons.co/ -> 3dicons
https://allaboutberlin.com -> Allaboutberlin

**Comment by Khushal-Pabri** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by ajhollid** [comment]
@Khushal-Pabri sure, go for it.

Please make a well formatted and descriptive PR when you're ready to go.

Thanks for your interest in the project!

**Comment by gorkem-bwl** [comment]
@Khushal-Pabri checking here. Are you still interested to send a PR for this issue?

**Comment by gorkem-bwl** [comment]
@shyna92 assigned to you, fyi.

**Comment by peterpardo** [comment]
@gorkem-bwl Hello! I can work on this. Can you assign me this issue?

**Comment by gorkem-bwl** [comment]
Yes, please go ahead. Make sure you run the app and test it live, and then send a video showing how it works.

**Comment by gorkem-bwl** [comment]
1. Yes, I assume it's better to do this way. If that doesn't work, or tricky, you can update the display name can be updated when the user sets the mouse cursor on the display name widget.

2. That is a good point. If the user changes the URL, it's surely another display name, hence it should be regenerated.

**Comment by peterpardo** [comment]
The **#1** is doable. But we just need to make sure that the URL they are inputting is valid.

I researched about valid domain names: 
- Only the special character Hyphen **"-"** is allowed in the domain name 
- Domain names should start with **a-z (case insensitive)** and **0-9** 
- Domain names can only have max 63 characters (not including the TLD)

We need to take this into account.

**Comment by peterpardo** [comment]
> The **#1** is doable. But we just need to make sure that the URL they are inputting is valid.
> 
> I researched about valid domain names:
> 
> * Only the special character Hyphen **"-"** is allowed in the domain name, but not at the beginning or at the end
> * Domain names can have **a-z (case insensitive)** and **0-9**
> * Domain names can only have max 63 characters (not including the TLD)
> 
> We need to take this into account.

Actually, we don't need to check if the URL is valid. Just discovered that it shows an alert saying that the URL endpoint doesn't resolve.

**Comment by peterpardo** [comment]
https://github.com/user-attachments/assets/ed46dcbd-e575-4f54-bb43-458b9dfa0ddb

@gorkem-bwl Here's the live app test. Let me know if there are things we need to change. Thanks!

**Comment by gorkem-bwl** [comment]
Perfect. That is simple and to the point. Thanks for this!

**Comment by peterpardo** [comment]
Cool! Should I proceed to create a PR for this?

**Comment by gorkem-bwl** [comment]
> Cool! Should I proceed to create a PR for this?

Yes. Thanks for this. CC @ajhollid

**Comment by ajhollid** [comment]
Hi @peterpardo ,

Yes there is an open PR for this one, but I am not especially attached to the solution, it's more of a proposal.

If you have a better way in mind, especially with regards to the algorithm for parsing the domain from a string, I would love to have your contribution!

**Comment by peterpardo** [comment]
Got it. I was looking at the PR you created, I think we can work around it. We just need to make sure that all edge cases when user types in a domain name is taken into account.

**Comment by peterpardo** [comment]
https://github.com/user-attachments/assets/80197cfa-2dc0-4698-834d-f24335c51b30

Hello @ajhollid ,

I used the branch that you have right now for this issue because I think it's better with the one I have right now and it catches most of the edge cases when typing in the domain name.

I just made some minor tweaks around the **parseDomainName** util you created. Let me know if this works for you.

I attached the live test of the app here @gorkem-bwl.

Thank you!

**Comment by peterpardo** [comment]
> checkmate-issue-992-demo-2.mp4 
> Hello @ajhollid ,
> 
> I used the branch that you have right now for this issue because I think it's better with the one I have right now and it catches most of the edge cases when typing in the domain name.
> 
> I just made some minor tweaks around the **parseDomainName** util you created. Let me know if this works for you.
> 
> I attached the live test of the app here @gorkem-bwl.
> 
> Thank you!

When the URL has a subdomain, e.g. "api.test.com", I just joined the two strings: `api.test.com -> "Api Test"`. Let me know if you want this behavior for these kinds of cases.

**Comment by gorkem-bwl** [comment]
It looks great to me @peterpardo . 

> When the URL has a subdomain, e.g. "api.test.com", I just joined the two strings: api.test.com -> "Api Test". Let me know if you want this behavior for these kinds of cases

Yes, this is a good approach. Thanks.

**Comment by peterpardo** [comment]
Awesome! Should I proceed to create a PR for this?

**Comment by ajhollid** [comment]
@peterpardo sure that sounds like a good approach to me.

If you want to build off my PR feel free to either branch off it and create a new PR or just push commits to this branch, either is fine 👌

**Comment by peterpardo** [comment]
Got it! Quick question, is this issue considered a `feat` or a `fix` to a bug?

**Comment by ajhollid** [comment]
> Got it! Quick question, is this issue considered a `feat` or a `fix` to a bug?

I think a feature as it is adding new functionality

**Comment by peterpardo** [comment]
Done! Created a PR for this, #1234, and is ready for review. Thanks!
